In [9]:
import tensorflow as tf
tf.__version__


'1.10.0'

In [10]:
# Create a constant op
# This op is added as a node to the default graph
hello = tf.constant("Hello, TensorFlow!")

# seart a TF session
sess = tf.Session()

# run the op and get result
print(sess.run(hello))

 

b'Hello, TensorFlow!'


In [20]:
t = tf.constant([[1,2],
                 [3,4]])

aaa=tf.shape(t)

print(sess.run(aaa))

 

[2 2]


In [12]:
import numpy as np
import pprint as pp
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint( t)


array([0., 1., 2., 3., 4., 5., 6.])


In [84]:
t = np.array([[[0, 1, 1], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]] ]) 
 
sess.run(tf.reshape(t, shape=[-1, 3]))

array([[ 0,  1,  1],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
x = [[6, 1, 2],
     [2, 1, 4], ]


aa= tf.argmax(x,axis=0)
sess.run(aa)

array([0, 0, 1], dtype=int64)

In [60]:
xx= tf.one_hot([[0], [1], [1], [0]], depth=3)
sess.run(xx)

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 1., 0.]],

       [[1., 0., 0.]]], dtype=float32)

In [78]:
t = np.array([[0, 1, 2], [3, 4, 5] ])
pp.pprint(t.shape)
pp.pprint(t)
t1 = tf.transpose(t, [0, 1])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))


(2, 3)
array([[0, 1, 2],
       [3, 4, 5]])
(2, 3)
array([[0, 1, 2],
       [3, 4, 5]])
